# Generated by Django 3.2.25 on 2024-07-19 20:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_alter_city_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
