# Generated by Django 4.2.14 on 2024-07-21 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['created_date'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
    ]
